# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

scada:
  ip: 7.83.93.65
  projectName: "enms"
  nodeName: "enms"
  mqtt:
    port: 1883
    targetPort: 1883
    nodePort: 31883
    username: vetec
    password: vetec
    topic: "data"



persistentVolume:
#  path: /Users/Kimtaejun/helmCharts/volumes #
  path: /volumes #C:\Users\21thp\workDir\volumes /Users/Kimtaejun/helmCharts/volumes   # /run/desktop/mnt/host/c/Users/21thp/workDir/volumes #C:\Users\21thp\workDir\volumes #/C/Users/21thp/workDir/volumes
  enabled: true
  name: enms-volume
  storageClass: manual # hostpath #manual #local-storage
  capacity: 30Gi
  accessModes:
    - ReadWriteOnce
  reclaimPolicy: Retain
  nodeName: platek8s-master-node

ingress-nginx:
  enabled: false
  host: plate.team
  fullnameOverride: "vetec-ingress-nginx"
  controller:
    name: vetec-ingress-nginx
    ingressClassResource:
      enabled: true
      name: vetec-ingress-nginx
    service:
      externalIPs:
        - "112.216.32.6"
      loadBalancerIP: "112.216.32.6"
      externalTrafficPolicy: "Local"
      ports:
        http: 3722
        https: 444
  type: ClusterIP
#  type: LoadBalancer
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0ebaa521"
  enabled: true
#  annotations: {}
  host: "enms.maeil.com"
  path: "/"
  tls: false
  tlsSecret: ""

frontend:
  imageName: vetec/enms-frontend
  tag: "0ebaa521"
  port: 3722
  targetPort: 3722
timeseriesApi:
  enabled: true
  inamgeName: vetec/timeseries-api
  tag: "0ebaa521"
  imageName: vetec/enms-timeseries-api
  port: 8089
  targetPort: 8089
  replicas: 1
timeseriesSaver:
  enabled: true
  tag: "0ebaa521"
  imageName: vetec/enms-timeseries-saver
  port: 8084
  targetPort: 8084
  replicas: 1
timeseriesScheduler:
  enabled: true
  tag: "0ebaa521"
  imageName: vetec/enms-timeseries-scheduler
  port: 8084
  targetPort: 8084
  replicas: 1
frameApi:
  enabled: true
  tag: "0ebaa521"
  imageName: vetec/enms-backend
  port: 8038
  targetPort: 8038
  replicas: 1
influxdb2:
  enabled: false
  ip: 112.216.32.6
  adminUser:
    organization: "enms"
    bucket: "history"
    user: "vetec"
    password: "vetecP@ssw0rd3721@!#"
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
  service:
    type: ClusterIP
    port: 8086
    targetPort: 8086
    nodePort: 32086
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    subPath: "influxdb"
#    mountPath: /Users/Kimtaejun/helmCharts/volumes
    mountPath: /run/desktop/mnt/host/c/Users/21thp/workDir/volumes
    size: 50Gi
mariadb:
  enabled: true
  capacity: 10Gi
  port: 3721
  volumePermissions:
    enabled: true
  auth:
    rootPassword: "vetec3721!"
    database: "ems"
  primary:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      existingClaim: mariadb-pvc
      storageClass: local-storage
      type: pvc
      accessModes:
        - ReadWriteOnce
      subPath: mariadb
redis:
  ip: "127.0.0.1"
  enabled: true
  volumePermissions:
    enabled: true
  port: "6378"
  auth:
    enabled: true
    password: "vetec3721!"
  capacity: 8Gi
  architecture: standalone
  service:
    type: NodePort
    nodePorts:
      redis: 32379
  master:
    persistence:
      enabled: true
      existingClaim: redis-pvc
      storageClass: local-storage
      type: pvc
      accessModes:
        - ReadWriteOnce
      subPath: redis
    service:
      type: ClusterIP
      ports:
        redis: 6379

https://charts:
  bitnami:
    com/bitnami:
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
