replicaCount: 1
scada:
  ip: 112.216.32.6
  projectName: enms
  nodeName: enms
  mqtt:
    port: 1883
    targetPort: 1883
    nodePort: 31883
    username: vetec
    password: vetec
    topic: data
persistentVolume:
  path: /volumes
  enabled: true
  name: enms-volume
  storageClass: manual
  capacity: 30Gi
  accessModes:
  - ReadWriteOnce
  reclaimPolicy: Retain
  nodeName: platek8s-master-node
ingress-nginx:
  enabled: true
  host: plate.team
  controller:
    ingressClassResource:
      enabled: false
    service:
      loadBalancerIP: 10.4.0.5
      externalTrafficPolicy: Local
      ports:
        http: 80
        https: 443
  type: ClusterIP
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 0ebaa521
  enabled: true
  host: enms.maeil.com
  path: /
  tls: false
  tlsSecret: ''
frontend:
  imageName: vetec/pms-frontend
  tag: '435e0320'
  port: 3722
  targetPort: 3722
timeseriesApi:
  enabled: true
  inamgeName: vetec/timeseries-api
  tag: e572f72c
  imageName: vetec/pms-timeseries-api
  port: 8089
  targetPort: 8089
  replicas: 1
timeseriesSaver:
  enabled: true
  tag: '331e4897'
  imageName: vetec/pms-timeseries-saver
  port: 8084
  targetPort: 8084
  replicas: 1
timeseriesScheduler:
  enabled: true
  tag: 435e0320
  imageName: vetec/pms-timeseries-scheduler
  port: 8084
  targetPort: 8084
  replicas: 1
frameApi:
  enabled: true
  tag: a2b61062
  imageName: vetec/pms-frame-api
  port: 8038
  targetPort: 8038
  replicas: 1
influxdb2:
  enabled: false
  ip: 112.216.32.6
  adminUser:
    organization: primary
    bucket: history
    user: vetec
    password: vetecP@ssw0rd3721@!#
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  service:
    type: ClusterIP
    port: 8086
    targetPort: 8086
    nodePort: 32086
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    subPath: influxdb
    mountPath: /run/desktop/mnt/host/c/Users/21thp/workDir/volumes
    size: 50Gi
mariadb:
  enabled: true
  capacity: 10Gi
  port: 3721
  volumePermissions:
    enabled: true
  auth:
    rootPassword: vetec3721!
    database: ems
  primary:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      existingClaim: mariadb-pvc
      storageClass: local-storage
      type: pvc
      accessModes:
      - ReadWriteOnce
      subPath: mariadb
redis:
  ip: 127.0.0.1
  enabled: true
  volumePermissions:
    enabled: true
  port: '6378'
  auth:
    enabled: true
    password: vetec3721!
  capacity: 8Gi
  architecture: standalone
  service:
    type: NodePort
    nodePorts:
      redis: 32379
  master:
    persistence:
      enabled: true
      existingClaim: redis-pvc
      storageClass: local-storage
      type: pvc
      accessModes:
      - ReadWriteOnce
      subPath: redis
    service:
      type: ClusterIP
      ports:
        redis: 6379
https://charts:
  bitnami:
    com/bitnami: null
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
