replicaCount: 1
scada:
  ip: 127.0.0.1
  projectName: enms
  nodeName: enms
  mqtt:
    port: 1883
    targetPort: 1883
    nodePort: 31883
    username: vetec
    password: vetec
    topic: data
timezone: Asia/Seoul
persistentVolume:
  path: /run/desktop/mnt/host/d
  enabled: true
  name: enms-volume
  storageClass: manual
  capacity: 30Gi
  accessModes:
  - ReadWriteOnce
  reclaimPolicy: Retain
  nodeName: docker-desktop
ingress-nginx:
  enabled: false
  host: ''
  controller:
    ingressClassResource:
      enabled: false
    service:
      loadBalancerIP: 10.4.0.5
      externalTrafficPolicy: Local
      ports:
        http: 3722
        https: 443
  type: LoadBalancer
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 0ebaa521
  enabled: true
  host: enms.maeil.com
  path: /
  tls: false
  tlsSecret: ''
frontend:
  replicas: 1
  imageName: vetec/enms-frontend
  tag: fcdcd005
  port: 3722
  targetPort: 3722
timeseriesApi:
  enabled: true
  inamgeName: vetec/timeseries-api
  tag: 795e9ebe
  imageName: vetec/enms-timeseries-api
  port: 8089
  targetPort: 8089
  replicas: 1
timeseriesSaver:
  enabled: true
  tag: 01799ae9
  imageName: vetec/enms-timeseries-saver
  port: 8084
  targetPort: 8084
  replicas: 1
timeseriesScheduler:
  enabled: true
  tag: 795e9ebe
  imageName: vetec/enms-timeseries-scheduler
  port: 8084
  targetPort: 8084
  replicas: 1
frameApi:
  enabled: true
  tag: 01799ae9
  imageName: vetec/enms-frame-api
  port: 8038
  targetPort: 8038
  replicas: 1
influxdb2:
  enabled: false
  ip: ''
  adminUser:
    organization: primary
    bucket: history
    user: admin
    password: ''
    token: ''
  service:
    type: ClusterIP
    port: 8086
    targetPort: 8086
    nodePort: 32086
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    subPath: influxdb
    mountPath: /run/desktop/mnt/host/c/Users/21thp/workDir/volumes
    size: 50Gi
mariadb:
  enabled: true
  capacity: 1Gi
  port: 3721
  volumePermissions:
    enabled: true
  auth:
    rootPassword: vetec3721!
    database: ems
  primary:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      existingClaim: mariadb-pvc
      storageClass: local-storage
      type: pvc
      accessModes:
      - ReadWriteOnce
      subPath: mariadb
redis:
  ip: 127.0.0.1
  enabled: true
  volumePermissions:
    enabled: true
  port: '6378'
  auth:
    enabled: true
    password: vetec3721!
  capacity: 500Mi
  architecture: standalone
  service:
    type: NodePort
    nodePorts:
      redis: 32379
  master:
    persistence:
      enabled: true
      existingClaim: redis-pvc
      storageClass: local-storage
      type: pvc
      accessModes:
      - ReadWriteOnce
      subPath: redis
    service:
      type: ClusterIP
      ports:
        redis: 6379
https://charts:
  bitnami:
    com/bitnami: null
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
