{{ if .Values.timeseriesSaver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-frame-api-controller
spec:
  replicas: {{ .Values.frameApi.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app-frame-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app-frame-api
    spec:
      {{ if .Values.redis.enabled }}
      initContainers:
        - name: wait-for-mariadb
          image: bitnami/kubectl:latest
          command: [ 'sh', '-c', 'until kubectl get pods -l app.kubernetes.io/instance={{.Release.Name}} -l app.kubernetes.io/name=redis -n {{.Release.Namespace}} | grep Running; do echo waiting for mariadb; sleep 10; done;' ]
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-app-frame-api-pod
          image: "{{ .Values.frameApi.imageName }}:{{ .Values.frameApi.tag }}"
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "3Gi"
          env:
            - name: INFLUXDB_IP
              value: "influxdb2-{{ .Release.Name }}"
            - name: INFLUXDB_PORT
              value: "{{ .Values.influxdb2.service.port }}"
            - name: INFLUXDB_BUCKET
              value: "{{ .Values.influxdb2.adminUser.bucket }}"
            - name: INFLUXDB_ORG
              value: "{{ .Values.influxdb2.adminUser.organization }}"
            - name: INFLUXDB_TOKEN
              value: "{{ .Values.influxdb2.adminUser.token }}"
            - name: INFLUXDB_USERNAME
              value: "{{ .Values.influxdb2.adminUser.user }}"
            - name: INFLUXDB_PASSWORD
              value: "{{ .Values.influxdb2.adminUser.password }}"
            - name: SCADA_IP
              value: "{{ (printf "%s-mqtt-service" ( .Release.Name )) }}"
            - name: SCADA_PROJECT_NAME
              value: "{{ .Values.scada.projectName }}"
            - name: SCADA_NODE_NAME
              value: "{{ .Values.scada.nodeName }}"
            - name: MQTT_PORT
              value: "{{ .Values.scada.mqtt.port }}"
            - name: MQTT_USERNAME
              value: "{{ .Values.scada.mqtt.username }}"
            - name: MQTT_PASSWORD
              value: "{{ .Values.scada.mqtt.password }}"
            - name: MQTT_TOPIC
              value: "{{ .Values.scada.mqtt.topic }}"
            - name: MQTT_CLIENTID
              value: "enms-client-wejij342089j03" # {{ randAlphaNum 10 | quote }}"
            - name: REDIS_IP
              value: "{{ ternary (printf "%s-redis-master" (.Release.Name)) .Values.redis.ip  .Values.redis.enabled }}"
            - name: REDIS_PORT
              value: "{{ ternary 6379 (printf "%s" (.Values.redis.port))  .Values.redis.enabled }}"
            - name: REDIS_PASSWORD
              value: "{{ .Values.redis.auth.password }}"
            - name: DB_HOSTNAME
              value: "{{ ternary (printf "%s-mariadb" (.Release.Name)) .Values.redis.ip  .Values.mariadb.enabled }}"
            - name: DB_NAME
              value: "ems"
            - name: DB_PORT
              value: "{{ ternary 3306 .Values.mariadb.port  .Values.mariadb.enabled }}"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: "{{ .Values.mariadb.auth.rootPassword }}"
            - name: TIMESERIES_SAVER_HOSTNAME
              value: "{{.Release.Name}}-app-timeseries-saver-service"
            - name: TIMESERIES_SAVER_PORT
              value: "{{ .Values.timeseriesSaver.port }}"
            - name: TIMESERIES_API_HOSTNAME
              value: "{{.Release.Name}}-app-timeseries-api-service"
            - name: TIMESERIES_API_PORT
              value: "{{ .Values.timeseriesApi.port }}"
{{- end}}