{{- if .Values.frameApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-frame-api-service
spec:
  selector:
    app: {{ .Release.Name }}-app-frame-api
  ports:
  - protocol: TCP
    port: {{ .Values.frameApi.port }}
    targetPort: {{ .Values.frameApi.targetPort }}
  type: ClusterIP
{{- end}}