# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: app-frontend
#        image: vetec/frontend
        image: "{{ .Values.frontend.imageName }}:{{ .Values.frontend.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.targetPort }}

