# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-app-frontend-controller
spec:
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}-{{ .Release.Name }}-app-frontend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}-{{ .Release.Name }}-app-frontend
    spec:  
      containers:
      - name: {{ .Release.Namespace }}-{{ .Release.Name }}-app-frontend-pod
#        image: vetec/frontend
        image: "{{ .Values.frontend.imageName }}:{{ .Values.frontend.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.targetPort }}

 