apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.targetPort }}
  type: ClusterIP