apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.influxdb.port }}
      targetPort: {{ .Values.influxdb.targetPort }}
      nodePort: {{ .Values.influxdb.nodePort }}
  type: NodePort