apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
metadata:
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: mynginx-ingress
spec:
  rules:
    - host: enms.maeil.com
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-frontend
                port:
                  number: 3722
          # - path: /api
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: app-frame-api
          #       port:
          #         number: 8038
          # - path: /api/data
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: app-timeseries-api
          #       port:
          #         number: 8089
          # - path: /tsdb
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: app-timeseries-saver
          #       port:
          #         number: 8084

