{{- if (index .Values "ingress-nginx" "enabled") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;

  name: nginx-ingress
spec:
  rules:
    - host: {{.Release.Namespace}}.plate.team
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-frontend-service
                port:
                  number: {{ .Values.frontend.port }}

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-frame-api-service
                port:
                  number: {{ .Values.frameApi.port }}
        {{ if .Values.timeseriesApi.enabled }}
          - path: /api/data
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-timeseries-api-service
                port:
                  number: {{ .Values.timeseriesApi.port }}
        {{ end }}
        {{ if .Values.timeseriesSaver.enabled }}
          - path: /tsdb
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-timeseries-saver-service
                port:
                  number: {{ .Values.timeseriesSaver.port }}
        {{ end }}

{{- end -}}