apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-pvc  # 필요에 따라 이름을 조정하세요
spec:
  accessModes: {{ toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  resources:
    requests:
      storage: 100Mi
  volumeName: {{.Release.Namespace}}-{{.Release.Name }}-job-pv