apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc  # 필요에 따라 이름을 조정하세요
spec:
  accessModes: {{ toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mariadb.capacity }}
  volumeName: mariadb-{{ .Values.persistentVolume.name }}