{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-{{ .Values.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.mariadb.capacity }}
  volumeMode: Filesystem
  accessModes: {{ toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  local:
    path: {{ .Values.persistentVolume.path }}
  {{- if .Values.persistentVolume.nodeName }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.persistentVolume.nodeName }}
  {{- end }}
{{- end }}