apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-mqtt-service
subsets:
  - addresses:
      - ip: "{{ .Values.scada.ip }}"
    ports:
      - port: {{ .Values.scada.mqtt.targetPort }}