apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-mqtt-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.scada.mqtt.port }}
      targetPort: {{ .Values.scada.mqtt.targetPort }}
  type: ClusterIP