apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-mqtt-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.scada.mqtt.port }}
      targetPort: {{ .Values.scada.mqtt.targetPort }}
  type: ClusterIP