{{- if not .Values.ingressNginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "my-app.fullname" . }}-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name:  {{ include "my-app.fullname" . }}-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
{{- end }}
