{{- if not .Values.ingressNginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    upstream frontend {
      server {{ include "my-app.fullname" . }}-app-frontend-svc:{{ .Values.frontend.port }};
    }

    server {
      listen 80;
      server_name {{ include "my-app.fullname" . }}-app-frontend-svc;
      location / {
          proxy_pass http://frontend;
      }
    }

{{- end}}