{{- if not (index .Values "ingress-nginx" "enabled") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream frontend {
      server {{ .Release.Name }}-app-frontend-service:{{ .Values.frontend.port }};
    }
    upstream appFrameApi {
      server {{.Release.Name}}-app-frame-api-service:{{.Values.frameApi.port}};
    }

    upstream appTimeseriesApi {
      server {{.Release.Name}}-app-timeseries-api-service:{{.Values.timeseriesApi.port}};
    }
    upstream appTimeseriesSaver {
      server {{.Release.Name}}-app-timeseries-saver-service:{{.Values.timeseriesSaver.port}};
    }
    server {
      listen 80;
      server_name {{ .Release.Name }}-app-frontend-service;
      location / {
          proxy_pass http://frontend;
      }
      location /api {
          proxy_pass          http://appFrameApi;
          proxy_set_header    X-Real-IP $remote_addr;
          proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header    Host $http_host;
      }
      location /api/data {
          proxy_pass          http://appTimeseriesApi;
          proxy_set_header    X-Real-IP $remote_addr;
          proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header    Host $http_host;
      }

      location /tsdb {
          proxy_pass          http://appTimeseriesSaver;
          proxy_set_header    X-Real-IP $remote_addr;
          proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header    Host $http_host;
      }
    }

{{- end}}