{{- if not (index .Values "ingress-nginx" "enabled") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream frontend {
      server {{ .Release.Namespace }}-{{ .Release.Name }}-app-frontend-service:{{ .Values.frontend.port }};
    }

    server {
      listen 80;
      server_name {{ .Release.Namespace }}-{{ .Release.Name }}-app-frontend-service;
      location / {
          proxy_pass http://frontend;
      }
    }

{{- end}}