{{- if not .Values.ingressNginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-sercie
spec:
  type: {{ .Values.ingressNginx.type }}
  ports:
    - port: {{ .Values.ingressNginx.port }}
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-nginx
{{- end}}