{{- if not (index .Values "ingress-nginx" "enabled") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-nginx-sercie
spec:
  type: {{ (index .Values "ingress-nginx" "type") }}
  ports:
    - port: {{ (index .Values "ingress-nginx" "controller" "service" "ports" "http") }}
      targetPort: 80
  selector:
    app: {{ .Release.Namespace }}-{{ .Release.Name }}-nginx
{{- end}}