apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-list-rolebinding
  namespace: {{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: pods-list-role
  apiGroup: rbac.authorization.k8s.io