apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-app-timeseries-saver-controller
spec:
  replicas: {{ .Values.timeseriesApi.replicas }}
  selector:
    matchLabels:
      app: {{ include "my-app.fullname" . }}-app-timeseries-saver
  template:
    metadata:
      labels:
        app: {{ include "my-app.fullname" . }}-app-timeseries-saver
    spec:
      containers:
        - name: {{ include "my-app.fullname" . }}-app-timeseries-saver-pod
          image: "{{ .Values.timeseriesSaver.imageName }}:{{ .Values.timeseriesApi.tag }}"
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "3Gi"
          env:
            - name: INFLUXDB_IP
              value: influxdb
            - name: INFLUXDB_PORT
              value: "{{ .Values.influxdb.port }}"
            - name: INFLUXDB_BUCKET
              value: "{{ .Values.influxdb.bucket }}"
            - name: INFLUXDB_ORG
              value: "{{ .Values.influxdb.org }}"
            - name: INFLUXDB_TOKEN
              value: "{{ .Values.influxdb.token }}"
            - name: INFLUXDB_USERNAME
              value: "{{ .Values.influxdb.username }}"
            - name: INFLUXDB_PASSWORD
              value: "{{ .Values.influxdb.password }}"
            - name: SCADA_IP
              value: "{{ .Values.scada.ip }}"
            - name: MQTT_PORT
              value: "{{ .Values.scada.mqtt.port }}"
            - name: MQTT_USERNAME
              value: "{{ .Values.scada.mqtt.username }}"
            - name: MQTT_PASSWORD
              value: "{{ .Values.scada.mqtt.password }}"
            - name: MQTT_TOPIC
              value: "{{ .Values.scada.mqtt.topic }}"
            - name: REDIS_IP
              value: "{{ ternary (printf "%s-redis-master" (include "my-app.fullname" .)) .Values.redis.ip  .Values.redis.enabled }}"
            - name: REDIS_PORT
              value: "{{ ternary 6379 (printf "%s" (.Values.redis.port))  .Values.redis.enabled }}"
            - name: REDIS_PASSWORD
              value: "{{ .Values.redis.auth.password }}"
