apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-app-timeseries-api-controller
spec:
  replicas: {{ .Values.timeseriesSaver.replicas }}
  selector:
    matchLabels:
      app: {{ include "my-app.fullname" . }}-app-timeseries-api
  template:
    metadata:
      labels:
        app: {{ include "my-app.fullname" . }}-app-timeseries-api
    spec:
      containers:
        - name: {{ include "my-app.fullname" . }}-app-timeseries-api-pod
          image: "{{ .Values.timeseriesSaver.imageName }}:{{ .Values.timeseriesApi.tag }}"
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "3Gi"
          env:
            - name: INFLUXDB_IP
              value: influxdb
            - name: INFLUXDB_PORT
              value: "{{ .Values.influxdb.port }}"
            - name: INFLUXDB_BUCKET
              value: "{{ .Values.influxdb.bucket }}"
            - name: INFLUXDB_ORG
              value: "{{ .Values.influxdb.org }}"
            - name: INFLUXDB_TOKEN
              value: "{{ .Values.influxdb.token }}"
            - name: INFLUXDB_USERNAME
              value: "{{ .Values.influxdb.username }}"
            - name: INFLUXDB_PASSWORD
              value: "{{ .Values.influxdb.password }}"
