apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-app-timeeseries-saver-service
spec:
  selector:
    app: {{ include "my-app.fullname" . }}-app-timeseries-saver
  ports:
  - protocol: TCP
    port: {{ .Values.timeseriesSaver.port }}
    targetPort: {{ .Values.timeseriesSaver.targetPort }}
  type: ClusterIP