{{- if .Values.timeseriesSaver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-timeeseries-saver-service
spec:
  selector:
    app: {{ .Release.Name }}-app-timeseries-saver
  ports:
  - protocol: TCP
    port: {{ .Values.timeseriesSaver.port }}
    targetPort: {{ .Values.timeseriesSaver.targetPort }}
  type: ClusterIP
{{- end}}