apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-app-timeeseries-api-service
spec:
  selector:
    app: {{ .Release.Namespace }}-{{ .Release.Name }}-app-timeseries-api
  ports:
  - protocol: TCP
    port: {{ .Values.timeseriesApi.port }}
    targetPort: {{ .Values.timeseriesApi.targetPort }}
  type: ClusterIP