# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-app-frontend-controller
spec:
  selector:
    matchLabels:
      app: {{ include "my-app.fullname" . }}-app-frontend
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "my-app.fullname" . }}-app-frontend
    spec:
      containers:
      - name: {{ include "my-app.fullname" . }}-app-frontend-pod
#        image: vetec/frontend
        image: "{{ .Values.frontend.imageName }}:{{ .Values.frontend.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.targetPort }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-app-timeseries-api-controller
spec:
  replicas: {{ .Values.timeseriesApi.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-app.fullname" . }}-app-timeseries-api
  template:
    metadata:
      labels:
        app: {{ include "my-app.fullname" . }}-app-timeseries-api
    spec:
      containers:
        - name: {{ include "my-app.fullname" . }}-app-timeseries-api-pod
          image: "vetec/enms-timeseries-api:{{ .Values.timeseriesApi.tag }}"
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "3Gi"
          env:
            - name: INFLUXDB_IP
              value: influxdb
            - name: INFLUXDB_PORT
              value: "{{ .Values.influxdb.port }}"
            - name: INFLUXDB_BUCKET
              value: "{{ .Values.influxdb.bucket }}"
            - name: INFLUXDB_ORG
              value: "{{ .Values.influxdb.org }}"
            - name: INFLUXDB_TOKEN
              value: "{{ .Values.influxdb.token }}"
