{{- if .Values.timeseriesScheduler.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-app-timeeseries-scheduler-service
spec:
  selector:
    app: {{ .Release.Namespace }}-{{ .Release.Name }}-app-timeseries-scheduler
  ports:
  - protocol: TCP
    port: {{ .Values.timeseriesSaver.port }}
    targetPort: {{ .Values.timeseriesSaver.targetPort }}
  type: ClusterIP
{{- end}}